[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
sbi = { version = "0.3.0" }
riscv = { version = "0.16.0", features = ["s-mode"] }
fdt-rs = { version = "0.4.5", default-features = false }
slab = { version = "0.4.12", default-features = false }
buddy_system_allocator = { version = "0.13.0" }
