[package]
name = "Virt-OS-RISCV64"
version = "0.1.0"
edition = "2024"

[dependencies]
sbi = { version = "0.3.0" }
riscv = { version = "0.16.0", features = ["s-mode"] }
slab = { version = "0.4.12", default-features = false }
buddy_system_allocator = { version = "0.13.0" }
spin = "0.10.0"
fdt = "0.1.5"
virtio-drivers = { version = "0.13.0", features = ["alloc"] }
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
