[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
buddy_system_allocator = "0.13.0"
fdt-rs = { version = "0.4.5", default-features = false }
riscv = { version = "0.16.0", features = ["s-mode", "rt", "rt-v-trap"] }
riscv-rt = { version = "0.17.1", features = ["s-mode", "v-trap"] }
sbi = "0.3.0"
spin = "0.10.0"
