[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64 \
  -m 64M \
  -machine virt \
  -smp 4 \
  -display none \
  -chardev stdio,id=con0,mux=on \
  -mon chardev=con0 \
  -serial chardev:con0 \
  -device virtio-serial-device \
  -device virtconsole,chardev=con0 \
  -drive file=disk.img,format=raw,id=hd0 \
  -device virtio-blk-device,drive=hd0 \
  -s -S \
  -d int,guest_errors \
  -kernel"""
rustflags = [
  "-C", "link-arg=-T./linker.ld",
]