[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64 \
  -m 1G \
  -machine virt \
  -smp 4 \
  -nographic \
  -chardev stdio,id=char0,mux=on \
  -serial chardev:char0 \
  -mon chardev=char0 \
  -device virtio-serial-device \
  -device virtconsole,chardev=char0 \
  -drive file=disk.img,format=raw,id=hd0 \
  -device virtio-blk-device,drive=hd0 \
  -kernel"""
rustflags = [
  "-C", "link-arg=-T./linker.ld",
]